### ISSUE TITLE
app.py:113-113: get limit-per-user value from global...

### ISSUE THREAD

**Issue by 0pdd** [bloogrox/ssp-campaigns#13]
The puzzle `1-54692b88` in [`app.py`](https://github.com/bloogrox/ssp-campaigns/blob/master/app.py) (lines 113-113) has to be resolved: "get limit-per-user value from global settings"

The puzzle was created by aslan on 09-Jul-17. 

Estimate: 15 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by bloogrox** [comment]
https://github.com/bloogrox/ssp-campaigns/blob/master/services/subscriber_processor.py#L17
move this number to global variables

**Comment by 0pdd** [comment]
The puzzle `1-54692b88` has disappeared from the source code, that's why I closed this issue.
