### ISSUE TITLE
app.py:155-155: filter user by timezone

### ISSUE THREAD

**Issue by 0pdd** [bloogrox/ssp-campaigns#21]
The puzzle `11-e005e178` in [`app.py`](https://github.com/bloogrox/ssp-campaigns/blob/master/app.py) (lines 155-155) has to be resolved: "filter user by timezone"

The puzzle was created by aslan on 10-Jul-17. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by bloogrox** [comment]
annotate documents with timezone offset,
calculate timezone offsets by hour 
and query against this field

**Comment by bloogrox** [comment]
we have some users data in elasticsearch

every user has field `timezone-offset` which is integer and means 
-7 for New York
5 for Dhakka
and etc.

we want to take those users from database, whose local time now is X, Y, Z, ... hours

**Comment by masterofdaemon** [comment]
where should i put query?

**Comment by bloogrox** [comment]
https://github.com/bloogrox/ssp-campaigns/blob/master/services/subscriber.py#L9
it is Subscriber Service,
you provide method `get_subscribers` with filters by country, by hours, ... and then query

**Comment by 0pdd** [comment]
The puzzle `11-e005e178` has disappeared from the source code, that's why I closed this issue.
