### ISSUE TITLE
app.py:69-69: daily count check (campaign daily limit)

### ISSUE THREAD

**Issue by 0pdd** [bloogrox/ssp-campaigns#8]
The puzzle `1-4087555a` in [`app.py`](https://github.com/bloogrox/ssp-campaigns/blob/master/app.py) (lines 69-69) has to be resolved: "daily count check"

The puzzle was created by aslan on 09-Jul-17. 

Estimate: 15 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by bloogrox** [comment]
we store counters for campaigns in Redis

keys in Redis are - https://github.com/bloogrox/ssp-campaigns/issues/32

https://github.com/bloogrox/ssp-campaigns/blob/master/services/campaign_processor.py#L23
here we check total limit for campaign and daily limit for campaign

**Estimate: 30 minutes**
